version: '3'

services:
  redis:
    image: 'redis'

  static:
    build: './static/'
    volumes:
      - ./static/html:/html

  signal:
    build: './signal/'
    command: 'adev runserver app.py'
    volumes:
      - './signal:/app'
    environment:
      SIGNAL_DEBUG: 'true'
      PYTHONUNBUFFERED: 'true'
      HASH_URL: 'https://github.com/evalinit/evalindex/master/hashes/'

  proxy:
    build: './proxy/'
    ports:
      - '8000:80'
