version: '3'

services:
  static:
    build: './static/.'
    volumes:
      - ./static/html:/html

  signal:
    build: './signal/.'
    command: 'adev runserver app.py'
    volumes:
      - './signal:/app'
    env_file:
      - './signal/.env'

  proxy:
    build: './proxy/.'
    ports:
      - '8000:80'
